name: Model Evluation

# triggers : events 
on:
    pull_request:
        branches:
            - main

# code 
jobs:
    model-evluation:
        runs-on: ubuntu-latest  # os linux 

        # steps 
        steps:
            - name : Checkout code 
              uses: actions/checkout@v4
              
            - name : Setup CML
              uses: iterative/setup-cml@v1

            - name : Setup Python3.11
              uses: actions/setup-python@v4
              with:
                python-version: 3.11

            - name: Setup requirements 
              run:
                pip install -r requiremets.txt

            - name: Run Model Evaluation
              run: python app.py 

            - name: Write CML report
              env:
                REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                # Post reports as comments in GitHub PRs
                cat metrices.txt >> report.md
                cml comment create report.md
